# Generated by Django 3.0.6 on 2020-05-30 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivityPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name', models.CharField(max_length=200)),
                ('tz', models.CharField(max_length=200)),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
            ],
        ),
    ]
