# Generated by Django 3.0.6 on 2020-05-30 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivityperiod',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='useractivityperiod',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
